@startuml

'!theme bluegray

skinparam ArrowHeadColor black
skinparam ArrowColor black
skinparam Color black
skinparam actorStyle awesome

:Super Administrateur: as sadmin #Red/Yellow
:Administrateur: as admin #Blue/Green
:Modérateur: as mod #Purple/Pink
:Citoyen connecté: as user #Turquoise/Coral
:Citoyen: as visit #Navy/Orange

sadmin --> (Créer un compte Sadmin\n Admin et modérateur)

(Afficher le dash board des stats) as adminad
admin --> (Ajouter / éditer une ressource)
admin ---> (Supprimer / suspendre une ressource)
admin --> (Ajouter / éditer une catégorie)
admin ---> (Supprimer une catégorie)
admin --> (Lister / filtrer toutes les ressources)
admin ---> (Désactivation / activation des comptes user)
admin --> adminad
adminad ..> (Filtrer les stats) : extend
adminad ..> (Exporter les stats) : extend

mod --> (Modérer les commentaires)
mod --> (validation d'une ressource\npour la publication)

(Ajouter un commentaire\nsur une ressource) as userac
(Réponse à un commentaire) as userrc
(Démarrer une ressource\nde type Activité/Jeu) as userdr
user --> userac
user ---> userrc
user --> (Création / édition d'une ressource)
user ---> (Ajouter / supprimer une\nressource de ses favoris)
user --> (Indiquer une ressource comme\n exploitée / non exploitée)
user ---> (Mettre de côté une\nressource / Annuler)
user --> userdr
userdr ..> (Inviter d’autres participants) : extend
userdr ..> (Echanger des messages dans\nle cadre de la ressource avec\nles autres participants) : extend
user --> (Voir un dash board pour les\nstats de ses publications)
' TODO ??? quesaco
user --> (Afficher un tableau\nde bord de progression)
' TODO end

(Filtrer / trier les ressources) as visitft
(Afficher le contenu ressources) as visitac
(Lister les ressources /\n ressources restreintes) as visitlr
(Partage d'une publication) as visitpp
visitac ..> userac : extend
visitac ..> userrc : extend
visitac ..> (Mettre un like sur une ressource) : extend
visitft ..> visitpp : extend
visitac ..> visitpp : extend
visit --> (Créer un compte)
visitlr ..> visitft : extend
visit --> visitlr
visitlr ..> visitac : extend
@enduml
