networks:
  internal:
    driver: bridge

services:
  database:
    image: 'mariadb'
    ports:
      - '3306:3306'
    container_name: db
    networks:
      - internal
    env_file: "front.env"
    volumes:
      - './data/db/:/var/lib/mysql'
    healthcheck:
      test: "mariadb --user=$MARIADB_USER --password=$MARIADB_PASSWORD --execute 'SHOW DATABASES;' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    container_name: phpmyadmin
    networks:
      - internal
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - database
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    networks:
      - internal
    ports:
      - '3000:3000'
    depends_on:
      database :
        condition: service_healthy
    env_file: "front.env"
    volumes:
      - .:/app
      - /app/node_modules
    command: "./start-dev.sh"
    # command: ["sleep", "infinity"]
