help:
	@echo cmig: create migration
	@echo runmig: run migration
	@echo revmig: revert migration
cmig:
	npm run typeorm:create-migration
runmig:
	npm run typeorm:run-migrations
revmig:
	npm run typeorm:revert-migrations
fixture:
	npm run fixture:apply