@startuml

!theme sunlust


skinparam ArrowHeadColor black
skinparam ArrowColor black
skinparam Color black
skinparam actorStyle awesome

:Super Administrateur: as sadmin #Red/Yellow
:Administrateur: as admin #Blue/Green
:Modérateur: as mod #Purple/Pink


sadmin --> (Créer un compte Sadmin\n Admin et modérateur)

(Afficher le dash board des stats) as adminad
admin --> (Ajouter / éditer une ressource)
admin ---> (Supprimer / suspendre une ressource)
admin --> (Ajouter / éditer une catégorie)
admin ---> (Supprimer une catégorie)
admin --> (Lister / filtrer toutes les ressources)
admin ---> (Désactivation / activation des comptes user)
admin --> (Lister les utilisateurs)
admin --> adminad
adminad ..> (Filtrer les stats) : extend
adminad ..> (Exporter les stats) : extend

mod --> (Modérer les commentaires)
mod ---> (Validation d'une ressource\npour la publication)
mod --> (Afficher les signalements dans un dash board)
mod ---> (Bannir un utilisateur signalé)
mod --> (Signaler comme lu le signalement)


newpage

!theme sunlust

skinparam ArrowHeadColor black
skinparam ArrowColor black
skinparam Color black
skinparam actorStyle awesome

:Citoyen connecté: as user #Turquoise/Coral
:Citoyen: as visit #Navy/Orange

rectangle "Doit se connecter" as SeCo {
(Ajouter un commentaire\nsur une ressource) as userac
(Réponse à un commentaire) as userrc
(Mettre un like sur une ressource) as userli
}
(Démarrer une ressource\nde type Activité/Jeu) as userdr
user --> SeCo
user ---> userdr
userdr ..> (Inviter d’autres participants) : extend
userdr ..> (Echanger des messages dans le cadre de la ressource avec les autres participants) : extend

user --> (Création / édition d'une ressource)
user --> (Ajouter / retirer une\nressource de ses favoris)
user ---> (Indiquer une \n ressource comme \n exploitée / non exploitée)
user --> (Mettre de côté une\nressource / Annuler)
user ----> (Voir un dash board pour les\nstats de ses publications)
user ---> (Modifier ses informations de connexion)
user --> (Ajouter une photo de profil)
user ---> (Signaler un utilisateur)

(Filtrer les ressources) as visitf
(Trier les ressources) as visitt
(Afficher le contenu \n d'une ressources) as visitac
(Lister les ressources /\n ressources restreintes) as visitlr
(Partage d'une publication) as visitpp
(Créer un compte) as creer

visitt .> visitpp : extend
visitf .> visitpp : extend
visitac ..> visitpp : extend
visit -> creer
visitlr ..> visitt : extend
visitlr ..> visitf : extend
visit --> visitlr
visitlr ..> visitac : extend
SeCo .> creer : include
visitac .> SeCo : extend
'todo verifier si il faut séparer lister et filtrer
@enduml
