@startuml diagrammeDeClasse

class User {
    -id: int
    -login: string
    -password: string
    -role: array
    -banned: boolean
    -createdAt: datetime
    -updatedAt: datetime
}

abstract class Ressource{
    -id: int
    -titre: string
    -contenu: string
    -datetimeCreation: datetime
    -validationAdmin: boolean
    -datetimeValidationAdmin: datetime
    -suspendu: boolean
    -deleted: boolean
}

class Video{
    -url: string
}

class Photo{
    -url: string
}

class Activite{
    -reponse: string
}

class Categorie{
    -id: int
    -nom: string
    -icone: string
    -datetimeCreation: datetime
    -deleted: boolean
}

class Commentaire{
    -id: int
    -message: string
    -datetimeCreation: datetime
    -deleted: boolean
}

class Favoris{
    -datetimeCreation: datetime
}

class APlusTard{
    -datetimeCreation: datetime
}

class Realisation{
    -datetimeCreation: datetime
    -tempsRealisation: time
}


' Besoin des Categorie
Categorie "0..*" --> "1..1" User : est crée par

' Besoin des ressources
Ressource "0..*" --> "1..1" Categorie : appartient à
Ressource "0..*" --> "1..1" User : est crée par
Ressource "0..*" --> "1..1" User : est validée par

' Besoin des commentaires
Commentaire "0..*" --> "1..1" User : est écrit par
Commentaire "0..*" --> "1..1" Commentaire : est une réponse à
Commentaire "0..*" --> "1..1" Ressource : est écrit sur

' Besoin des favoris
Favoris "0..*" --> "1..1" User : est mit en favoris par
Favoris "0..*" --> "1..1" Ressource : est mit en favoris

' Besoin des mit en plus tard
APlusTard "0..*" --> "1..1" User : est mit en plus tard par
APlusTard "0..*" --> "1..1" Ressource : est mit en plus tard

' Besoin des réalisations
Realisation "0..*" --> "1..1" User : est réalisé par
Realisation "0..*" --> "1..1" Activite : est réalisé

Ressource <|-- Video
Ressource <|-- Photo
Ressource <|-- Activite


@enduml