name: CI Pipeline
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
permissions:
  contents: read
env:
  WORKDIR: ./api
jobs:
  docker:
    environment: Api
    name: Docker Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate timestamp tag
        id: tag
        run: |
          echo "TAG=$(date +'${{ vars.TIME_TAG_FORMAT }}')" >> $GITHUB_ENV
      - name: Build and push Docker image for the api
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/backend.Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_APPLICATION_NAME }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.BACKEND_APPLICATION_NAME }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Docker image for the front
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/frontend.Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.FRONTEND_APPLICATION_NAME }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.FRONTEND_APPLICATION_NAME }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max